/*
 * Surogate Hub API
 * Surogate Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.surogate.hub.clients.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.surogate.hub.clients.sdk.model.UsageReport;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InstallationUsageReport
 */
public class InstallationUsageReportTest {
    private final InstallationUsageReport model = new InstallationUsageReport();

    /**
     * Model tests for InstallationUsageReport
     */
    @Test
    public void testInstallationUsageReport() {
        // TODO: test InstallationUsageReport
    }

    /**
     * Test the property 'installationId'
     */
    @Test
    public void installationIdTest() {
        // TODO: test installationId
    }

    /**
     * Test the property 'reports'
     */
    @Test
    public void reportsTest() {
        // TODO: test reports
    }

}
