"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

NAME = "surogate-hub-sdk"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

PYTHON_REQUIRES = ">=3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2.0.0",
    "aenum",
    "fsspec >= 2024.0.0",
    "duckdb == 1.5.2",
    "hf_xet == 1.4.3",
]

with open('README.md') as f:
    import re
    # replace relative links with links to the docs:
    doc_version = '.'.join(f'v{VERSION}'.split('.')[:2])
    long_description = re.sub(r'(\[[*a-zA-Z_]*]\()docs/([A-Za-z0-9]*)\.md',
                       rf'\1https://pydocs-sdk.sghub.io/{doc_version}/docs/\2.html',
                       f.read())

setup(
    name=NAME,
    version=VERSION,
    description="Surogate Hub API",
    author="Invergent",
    author_email="contact@invergent.ai",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Surogate Hub API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description=long_description,
    long_description_content_type='text/markdown'
)
