{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shub.fullname" . }}
  labels:
    {{- include "shub.labels" . | nindent 4 }}
type: Opaque
data:
{{- if (.Values.secrets).databaseConnectionString }}
  database_connection_string: {{ .Values.secrets.databaseConnectionString | default "" | b64enc }}
{{- end }}
{{- if (.Values.secrets).authEncryptSecretKey }}
  auth_encrypt_secret_key: {{ .Values.secrets.authEncryptSecretKey | default "" | b64enc }}
{{- end }}
{{- end }}
---
{{- if and .Values.image.privateRegistry.enabled .Values.image.privateRegistry.secretToken }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "shub.dockerConfigJson" . }}
{{- end }}