# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from surogate_hub_sdk.models.owner_storage_repo import OwnerStorageRepo
from typing import Optional, Set
from typing_extensions import Self

class OwnerStorage(BaseModel):
    """
    OwnerStorage
    """ # noqa: E501
    owner: StrictStr = Field(description="The repository owner namespace — the first path segment of every repo id this payload aggregates over. Not necessarily a registered hub auth user. ")
    bytes_used: StrictInt
    quota_bytes: Optional[StrictInt] = None
    bytes_remaining: Optional[StrictInt] = None
    repositories: List[OwnerStorageRepo]
    last_reconciled_at: Optional[datetime] = None
    is_estimate: StrictBool
    __properties: ClassVar[List[str]] = ["owner", "bytes_used", "quota_bytes", "bytes_remaining", "repositories", "last_reconciled_at", "is_estimate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OwnerStorage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in repositories (list)
        _items = []
        if self.repositories:
            for _item_repositories in self.repositories:
                if _item_repositories:
                    _items.append(_item_repositories.to_dict())
            _dict['repositories'] = _items
        # set to None if quota_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.quota_bytes is None and "quota_bytes" in self.model_fields_set:
            _dict['quota_bytes'] = None

        # set to None if bytes_remaining (nullable) is None
        # and model_fields_set contains the field
        if self.bytes_remaining is None and "bytes_remaining" in self.model_fields_set:
            _dict['bytes_remaining'] = None

        # set to None if last_reconciled_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_reconciled_at is None and "last_reconciled_at" in self.model_fields_set:
            _dict['last_reconciled_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OwnerStorage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "owner": obj.get("owner"),
            "bytes_used": obj.get("bytes_used"),
            "quota_bytes": obj.get("quota_bytes"),
            "bytes_remaining": obj.get("bytes_remaining"),
            "repositories": [OwnerStorageRepo.from_dict(_item) for _item in obj["repositories"]] if obj.get("repositories") is not None else None,
            "last_reconciled_at": obj.get("last_reconciled_at"),
            "is_estimate": obj.get("is_estimate")
        })
        return _obj


