# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.models.external_principal import ExternalPrincipal

class TestExternalPrincipal(unittest.TestCase):
    """ExternalPrincipal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalPrincipal:
        """Test ExternalPrincipal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalPrincipal`
        """
        model = ExternalPrincipal()
        if include_optional:
            return ExternalPrincipal(
                id = '',
                user_id = '',
                settings = [
                    {
                        'key' : ''
                        }
                    ]
            )
        else:
            return ExternalPrincipal(
                id = '',
                user_id = '',
        )
        """

    def testExternalPrincipal(self):
        """Test ExternalPrincipal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
