# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.models.owner_quota import OwnerQuota

class TestOwnerQuota(unittest.TestCase):
    """OwnerQuota unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OwnerQuota:
        """Test OwnerQuota
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OwnerQuota`
        """
        model = OwnerQuota()
        if include_optional:
            return OwnerQuota(
                quota_bytes = 0
            )
        else:
            return OwnerQuota(
                quota_bytes = 0,
        )
        """

    def testOwnerQuota(self):
        """Test OwnerQuota"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
