# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.models.user_storage import UserStorage

class TestUserStorage(unittest.TestCase):
    """UserStorage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserStorage:
        """Test UserStorage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserStorage`
        """
        model = UserStorage()
        if include_optional:
            return UserStorage(
                user = '',
                bytes_used = 56,
                quota_bytes = 56,
                bytes_remaining = 56,
                repositories = [
                    surogate_hub_sdk.models.user_storage_repo.UserStorageRepo(
                        name = '', 
                        bytes_used = 56, )
                    ],
                last_reconciled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_estimate = True
            )
        else:
            return UserStorage(
                user = '',
                bytes_used = 56,
                repositories = [
                    surogate_hub_sdk.models.user_storage_repo.UserStorageRepo(
                        name = '', 
                        bytes_used = 56, )
                    ],
                is_estimate = True,
        )
        """

    def testUserStorage(self):
        """Test UserStorage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
