# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.api.storage_api import StorageApi


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StorageApi()

    def tearDown(self) -> None:
        pass

    def test_delete_owner_quota(self) -> None:
        """Test case for delete_owner_quota

        clear an owner namespace's storage quota
        """
        pass

    def test_get_owner_storage(self) -> None:
        """Test case for get_owner_storage

        get an owner namespace's storage usage and quota
        """
        pass

    def test_set_owner_quota(self) -> None:
        """Test case for set_owner_quota

        set an owner namespace's storage quota
        """
        pass


if __name__ == '__main__':
    unittest.main()
