# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.models.repository_list import RepositoryList

class TestRepositoryList(unittest.TestCase):
    """RepositoryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepositoryList:
        """Test RepositoryList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepositoryList`
        """
        model = RepositoryList()
        if include_optional:
            return RepositoryList(
                pagination = surogate_hub_sdk.models.pagination.Pagination(
                    has_more = True, 
                    next_offset = '', 
                    results = 0, 
                    max_per_page = 0, ),
                results = [
                    surogate_hub_sdk.models.repository.Repository(
                        id = '', 
                        creation_date = 56, 
                        default_branch = '', 
                        storage_id = '', 
                        storage_namespace = '', 
                        read_only = True, 
                        metadata = {
                            'key' : ''
                            }, )
                    ]
            )
        else:
            return RepositoryList(
                pagination = surogate_hub_sdk.models.pagination.Pagination(
                    has_more = True, 
                    next_offset = '', 
                    results = 0, 
                    max_per_page = 0, ),
                results = [
                    surogate_hub_sdk.models.repository.Repository(
                        id = '', 
                        creation_date = 56, 
                        default_branch = '', 
                        storage_id = '', 
                        storage_namespace = '', 
                        read_only = True, 
                        metadata = {
                            'key' : ''
                            }, )
                    ],
        )
        """

    def testRepositoryList(self):
        """Test RepositoryList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
