# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.models.stats_event import StatsEvent

class TestStatsEvent(unittest.TestCase):
    """StatsEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsEvent:
        """Test StatsEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsEvent`
        """
        model = StatsEvent()
        if include_optional:
            return StatsEvent(
                var_class = '',
                name = '',
                count = 56
            )
        else:
            return StatsEvent(
                var_class = '',
                name = '',
                count = 56,
        )
        """

    def testStatsEvent(self):
        """Test StatsEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
