# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.api.config_api import ConfigApi


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigApi()

    def tearDown(self) -> None:
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
