# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.models.ref_list import RefList

class TestRefList(unittest.TestCase):
    """RefList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefList:
        """Test RefList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefList`
        """
        model = RefList()
        if include_optional:
            return RefList(
                pagination = surogate_hub_sdk.models.pagination.Pagination(
                    has_more = True, 
                    next_offset = '', 
                    results = 0, 
                    max_per_page = 0, ),
                results = [
                    surogate_hub_sdk.models.ref.Ref(
                        id = '', 
                        commit_id = '', )
                    ]
            )
        else:
            return RefList(
                pagination = surogate_hub_sdk.models.pagination.Pagination(
                    has_more = True, 
                    next_offset = '', 
                    results = 0, 
                    max_per_page = 0, ),
                results = [
                    surogate_hub_sdk.models.ref.Ref(
                        id = '', 
                        commit_id = '', )
                    ],
        )
        """

    def testRefList(self):
        """Test RefList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
