"""Tests for surogate_hub_sdk.parquet.

These do not hit a live hub — the ObjectsApi is mocked so ``physical_address``
points at a local file:// URL, which DuckDB's httpfs can read directly.
"""

import io
import os
import tempfile
import unittest
from unittest.mock import MagicMock

try:
    import pyarrow as pa
    import pyarrow.parquet as pq_writer
except ImportError:  # pragma: no cover
    pa = None

from surogate_hub_sdk.exceptions import ApiException, NotFoundException
from surogate_hub_sdk.models.object_stats import ObjectStats
from surogate_hub_sdk.models.object_stats_list import ObjectStatsList
from surogate_hub_sdk.models.pagination import Pagination


class PresignUnsupportedDetectionTest(unittest.TestCase):
    def test_xet_presign_rejection_is_fallback_condition(self):
        from surogate_hub_sdk.parquet.query import _is_presign_unsupported

        exc = ApiException(
            status=400, reason="Bad Request",
            body='{"message":"xet physical address cannot be presigned"}',
        )

        self.assertTrue(_is_presign_unsupported(exc))


class InMemoryObjectStore:
    """Tiny in-memory SDK fake used by the presign-fallback tests below.

    Inlined here rather than factored into a shared module because
    ``clients/python/test/`` is regenerated by the OpenAPI generator —
    side-channel files there get wiped.
    """

    def __init__(self, objects):
        self._objects = dict(objects)

    def _stats(self, path):
        return ObjectStats(
            path=path, path_type="object",
            physical_address=f"mem://{path}", checksum="x",
            size_bytes=len(self._objects[path]), mtime=0,
        )

    def list_objects(self, *, user, repository, ref, prefix, delimiter=None,
                     after=None, amount=None, presign=None):
        if (user, repository) != ("owner", "repo"):
            raise AssertionError(
                f"expected owner/repo, got user={user!r} repository={repository!r}"
            )
        results = []
        seen = set()
        for p in sorted(x for x in self._objects if x.startswith(prefix or "")):
            tail = p[len(prefix):]
            if delimiter and delimiter in tail:
                common = prefix + tail.split(delimiter, 1)[0] + delimiter
                if common in seen:
                    continue
                seen.add(common)
                results.append(ObjectStats(
                    path=common, path_type="common_prefix",
                    physical_address="", checksum="", size_bytes=0, mtime=0,
                ))
            else:
                results.append(self._stats(p))
        return ObjectStatsList(
            pagination=Pagination(has_more=False, next_offset="",
                                  results=len(results), max_per_page=amount or 1000),
            results=results,
        )

    def stat_object(self, *, user, repository, ref, path, presign=None):
        if (user, repository) != ("owner", "repo"):
            raise AssertionError(
                f"expected owner/repo, got user={user!r} repository={repository!r}"
            )
        if path not in self._objects:
            raise NotFoundException(status=404, reason="Not Found")
        return self._stats(path)

    def get_object(self, *, user, repository, ref, path, range=None, **_):
        if (user, repository) != ("owner", "repo"):
            raise AssertionError(
                f"expected owner/repo, got user={user!r} repository={repository!r}"
            )
        if path not in self._objects:
            raise NotFoundException(status=404, reason="Not Found")
        data = self._objects[path]
        if range:
            start_s, end_s = range[len("bytes="):].split("-")
            return bytearray(data[int(start_s): int(end_s) + 1])
        return bytearray(data)


@unittest.skipIf(pa is None, "pyarrow not installed")
class ParquetQueryTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.files = {}
        for i in range(2):
            tbl = pa.table({
                "id": list(range(i * 10, i * 10 + 10)),
                "country": ["US" if j % 2 == 0 else "UK" for j in range(10)],
            })
            path = os.path.join(self.tmp, f"events_{i}.parquet")
            pq_writer.write_table(tbl, path)
            self.files[f"events/events_{i}.parquet"] = path

    def _build_query(self):
        from surogate_hub_sdk.parquet import ParquetQuery

        pq = ParquetQuery.__new__(ParquetQuery)
        pq._api_client = MagicMock()
        pq._objects = self._mock_objects_api()
        pq._list_page_size = 1000
        pq._duckdb_threads = None
        pq._presign_supported = None
        return pq

    def _mock_objects_api(self):
        api = MagicMock()

        def _stats(path):
            return ObjectStats(
                path=path,
                path_type="object",
                physical_address=f"file://{self.files[path]}",
                checksum="x",
                size_bytes=1,
                mtime=0,
            )

        def _stat_object(user, repository, ref, path, presign):
            if (user, repository) != ("owner", "repo"):
                raise AssertionError(
                    f"expected owner/repo, got user={user!r} repository={repository!r}"
                )
            return _stats(path)

        api.stat_object.side_effect = _stat_object
        api.list_objects.return_value = ObjectStatsList(
            pagination=Pagination(
                has_more=False, next_offset="", results=len(self.files), max_per_page=1000,
            ),
            results=[_stats(p) for p in self.files],
        )
        return api

    def test_read_exact_file_with_projection_and_limit(self):
        pq = self._build_query()
        table = pq.read(
            "owner/repo", "main", "events/events_0.parquet",
            columns=["country"], limit=3,
        )
        self.assertEqual(table.column_names, ["country"])
        self.assertEqual(table.num_rows, 3)

    def test_read_glob_aggregates_across_files(self):
        pq = self._build_query()
        table = pq.read("owner/repo", "main", "events/*.parquet")
        self.assertEqual(table.num_rows, 20)

    def test_sql_with_named_table(self):
        pq = self._build_query()
        table = pq.sql(
            "owner/repo", "main",
            "SELECT country, COUNT(*) c FROM {e} GROUP BY country ORDER BY country",
            tables={"e": "events/*.parquet"},
        )
        result = {row["country"]: row["c"] for row in table.to_pylist()}
        self.assertEqual(result, {"UK": 10, "US": 10})

    def test_bad_alias_rejected(self):
        from surogate_hub_sdk.parquet import ParquetQueryError

        pq = self._build_query()
        with self.assertRaises(ParquetQueryError):
            pq.sql("owner/repo", "main", "SELECT 1", tables={"not an ident": "x"})


@unittest.skipIf(pa is None, "pyarrow not installed")
class ParquetQueryPresignFallbackTest(unittest.TestCase):
    """When the hub's blockstore can't presign, ParquetQuery should switch
    to fsspec mode (shub:// URLs routed through SurogateHubFileSystem) and
    still return the correct data."""

    def setUp(self):
        from surogate_hub_sdk.fs import SurogateHubFileSystem

        tbl = pa.table({"id": [1, 2, 3], "text": ["a", "b", "c"]})
        buf = io.BytesIO()
        pq_writer.write_table(tbl, buf, compression="zstd")
        self.store = InMemoryObjectStore({"data/train.parquet": buf.getvalue()})

        SurogateHubFileSystem._cache.clear()
        self._original_init = SurogateHubFileSystem.__init__
        store = self.store

        def _patched(self, host=None, username=None, password=None, *, api_client=None, **kw):
            from fsspec.spec import AbstractFileSystem

            AbstractFileSystem.__init__(self, **kw)
            self._api_client = None
            self._objects = store
            self._repos = store
            self._list_page_size = 1000

        self._patched_init = _patched
        SurogateHubFileSystem.__init__ = _patched

    def tearDown(self):
        from surogate_hub_sdk.fs import SurogateHubFileSystem

        SurogateHubFileSystem.__init__ = self._original_init
        SurogateHubFileSystem._cache.clear()

    def _presign_unsupported(self, *, status=400):
        return ApiException(
            status=status, reason="Bad Request",
            body='{"message":"local adapter presigned URL: operation not supported"}',
        )

    def _xet_presign_unsupported(self):
        return ApiException(
            status=400, reason="Bad Request",
            body='{"message":"xet physical address cannot be presigned"}',
        )

    def test_exact_path_falls_back_to_shub(self):
        from surogate_hub_sdk.parquet import ParquetQuery

        pq = ParquetQuery.__new__(ParquetQuery)
        pq._objects = MagicMock()
        pq._objects.stat_object.side_effect = self._presign_unsupported()
        pq._api_client = MagicMock()
        pq._list_page_size = 1000
        pq._duckdb_threads = None
        pq._presign_supported = None

        table = pq.read("owner/repo", "main", "data/train.parquet")
        self.assertEqual(table.num_rows, 3)
        self.assertEqual(table.column("text").to_pylist(), ["a", "b", "c"])
        # Decision cached — next call skips the presign attempt.
        self.assertIs(pq._presign_supported, False)

    def test_xet_presign_rejection_falls_back_to_shub(self):
        from surogate_hub_sdk.parquet import ParquetQuery

        pq = ParquetQuery.__new__(ParquetQuery)
        pq._objects = MagicMock()
        pq._objects.stat_object.side_effect = self._xet_presign_unsupported()
        pq._api_client = MagicMock()
        pq._list_page_size = 1000
        pq._duckdb_threads = None
        pq._presign_supported = None

        table = pq.read("owner/repo", "main", "data/train.parquet")
        self.assertEqual(table.num_rows, 3)
        self.assertEqual(table.column("text").to_pylist(), ["a", "b", "c"])
        self.assertIs(pq._presign_supported, False)

    def test_glob_falls_back_to_shub_listing(self):
        from surogate_hub_sdk.parquet import ParquetQuery

        api = MagicMock()

        def _list(**kw):
            if kw.get("presign") is True:
                raise self._presign_unsupported()
            return self.store.list_objects(**kw)

        api.list_objects.side_effect = _list

        pq = ParquetQuery.__new__(ParquetQuery)
        pq._objects = api
        pq._api_client = MagicMock()
        pq._list_page_size = 1000
        pq._duckdb_threads = None
        pq._presign_supported = None

        table = pq.read("owner/repo", "main", "data/*.parquet")
        self.assertEqual(table.num_rows, 3)
        self.assertIs(pq._presign_supported, False)

    def test_other_400_is_not_treated_as_presign_failure(self):
        from surogate_hub_sdk.parquet import ParquetQuery

        pq = ParquetQuery.__new__(ParquetQuery)
        pq._objects = MagicMock()
        pq._objects.stat_object.side_effect = ApiException(
            status=400, reason="Bad Request",
            body='{"message":"some other validation error"}',
        )
        pq._api_client = MagicMock()
        pq._list_page_size = 1000
        pq._duckdb_threads = None
        pq._presign_supported = None

        with self.assertRaises(ApiException):
            pq.read("owner/repo", "main", "data/train.parquet")
        self.assertIsNone(pq._presign_supported)


if __name__ == "__main__":
    unittest.main()
