# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.models.owner_storage_repo import OwnerStorageRepo

class TestOwnerStorageRepo(unittest.TestCase):
    """OwnerStorageRepo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OwnerStorageRepo:
        """Test OwnerStorageRepo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OwnerStorageRepo`
        """
        model = OwnerStorageRepo()
        if include_optional:
            return OwnerStorageRepo(
                name = '',
                bytes_used = 56
            )
        else:
            return OwnerStorageRepo(
                name = '',
                bytes_used = 56,
        )
        """

    def testOwnerStorageRepo(self):
        """Test OwnerStorageRepo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
