# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.api.staging_api import StagingApi


class TestStagingApi(unittest.TestCase):
    """StagingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StagingApi()

    def tearDown(self) -> None:
        pass

    def test_get_physical_address(self) -> None:
        """Test case for get_physical_address

        generate an address to which the client can upload an object
        """
        pass

    def test_link_physical_address(self) -> None:
        """Test case for link_physical_address

        associate staging on this physical address with a path
        """
        pass


if __name__ == '__main__':
    unittest.main()
