# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.api.commits_api import CommitsApi


class TestCommitsApi(unittest.TestCase):
    """CommitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommitsApi()

    def tearDown(self) -> None:
        pass

    def test_commit(self) -> None:
        """Test case for commit

        create commit
        """
        pass

    def test_get_commit(self) -> None:
        """Test case for get_commit

        get commit
        """
        pass


if __name__ == '__main__':
    unittest.main()
