# coding: utf-8

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from surogate_hub_sdk.api.import_api import ImportApi


class TestImportApi(unittest.TestCase):
    """ImportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportApi()

    def tearDown(self) -> None:
        pass

    def test_import_cancel(self) -> None:
        """Test case for import_cancel

        cancel ongoing import
        """
        pass

    def test_import_start(self) -> None:
        """Test case for import_start

        import data from object store
        """
        pass

    def test_import_status(self) -> None:
        """Test case for import_status

        get import status
        """
        pass


if __name__ == '__main__':
    unittest.main()
