# coding: utf-8

# flake8: noqa

"""
    Surogate Hub API

    Surogate Hub API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@invergent.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ActionsApi",
    "AuthApi",
    "BranchesApi",
    "CommitsApi",
    "ConfigApi",
    "ExperimentalApi",
    "ExternalApi",
    "HealthCheckApi",
    "ImportApi",
    "InternalApi",
    "MetadataApi",
    "ObjectsApi",
    "PullsApi",
    "RefsApi",
    "RepositoriesApi",
    "StagingApi",
    "TagsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ACL",
    "AbortPresignMultipartUpload",
    "AccessKeyCredentials",
    "ActionRun",
    "ActionRunList",
    "AuthCapabilities",
    "AuthenticationToken",
    "BranchCreation",
    "BranchProtectionRule",
    "CherryPickCreation",
    "CommPrefsInput",
    "Commit",
    "CommitCreation",
    "CommitList",
    "CommitOverrides",
    "CommitRecordCreation",
    "CompletePresignMultipartUpload",
    "Config",
    "Credentials",
    "CredentialsList",
    "CredentialsWithSecret",
    "CurrentUser",
    "Diff",
    "DiffList",
    "Error",
    "ErrorNoACL",
    "ExternalLoginInformation",
    "ExternalPrincipal",
    "ExternalPrincipalCreation",
    "ExternalPrincipalList",
    "FindMergeBaseResult",
    "GarbageCollectionConfig",
    "GarbageCollectionPrepareResponse",
    "GarbageCollectionRule",
    "GarbageCollectionRules",
    "Group",
    "GroupCreation",
    "GroupList",
    "HookRun",
    "HookRunList",
    "ImportCreation",
    "ImportCreationResponse",
    "ImportLocation",
    "ImportStatus",
    "InstallationUsageReport",
    "InternalDeleteBranchProtectionRuleRequest",
    "LoginConfig",
    "LoginInformation",
    "Merge",
    "MergeResult",
    "MetaRangeCreation",
    "MetaRangeCreationResponse",
    "ObjectCopyCreation",
    "ObjectError",
    "ObjectErrorList",
    "ObjectStageCreation",
    "ObjectStats",
    "ObjectStatsList",
    "ObjectUploadMode",
    "Pagination",
    "PathList",
    "Policy",
    "PolicyList",
    "PrepareGCUncommittedRequest",
    "PrepareGCUncommittedResponse",
    "PresignMultipartUpload",
    "PullRequest",
    "PullRequestBasic",
    "PullRequestCreation",
    "PullRequestCreationResponse",
    "PullRequestsList",
    "RangeMetadata",
    "Ref",
    "RefList",
    "RefsDump",
    "RefsRestore",
    "Repository",
    "RepositoryCreation",
    "RepositoryDumpStatus",
    "RepositoryList",
    "RepositoryMetadataKeys",
    "RepositoryMetadataSet",
    "RepositoryRestoreStatus",
    "ResetCreation",
    "RevertCreation",
    "Setup",
    "SetupState",
    "StagingLocation",
    "StagingMetadata",
    "Statement",
    "StatsEvent",
    "StatsEventsList",
    "StorageConfig",
    "StorageURI",
    "StsAuthRequest",
    "TagCreation",
    "TaskInfo",
    "UnderlyingObjectProperties",
    "UpdateObjectUserMetadata",
    "UpdateToken",
    "UploadPart",
    "UsageReport",
    "User",
    "UserCreation",
    "UserList",
    "VersionConfig",
]

# import apis into sdk package
from surogate_hub_sdk.api.actions_api import ActionsApi as ActionsApi
from surogate_hub_sdk.api.auth_api import AuthApi as AuthApi
from surogate_hub_sdk.api.branches_api import BranchesApi as BranchesApi
from surogate_hub_sdk.api.commits_api import CommitsApi as CommitsApi
from surogate_hub_sdk.api.config_api import ConfigApi as ConfigApi
from surogate_hub_sdk.api.experimental_api import ExperimentalApi as ExperimentalApi
from surogate_hub_sdk.api.external_api import ExternalApi as ExternalApi
from surogate_hub_sdk.api.health_check_api import HealthCheckApi as HealthCheckApi
from surogate_hub_sdk.api.import_api import ImportApi as ImportApi
from surogate_hub_sdk.api.internal_api import InternalApi as InternalApi
from surogate_hub_sdk.api.metadata_api import MetadataApi as MetadataApi
from surogate_hub_sdk.api.objects_api import ObjectsApi as ObjectsApi
from surogate_hub_sdk.api.pulls_api import PullsApi as PullsApi
from surogate_hub_sdk.api.refs_api import RefsApi as RefsApi
from surogate_hub_sdk.api.repositories_api import RepositoriesApi as RepositoriesApi
from surogate_hub_sdk.api.staging_api import StagingApi as StagingApi
from surogate_hub_sdk.api.tags_api import TagsApi as TagsApi

# import ApiClient
from surogate_hub_sdk.api_response import ApiResponse as ApiResponse
from surogate_hub_sdk.api_client import ApiClient as ApiClient
from surogate_hub_sdk.configuration import Configuration as Configuration
from surogate_hub_sdk.exceptions import OpenApiException as OpenApiException
from surogate_hub_sdk.exceptions import ApiTypeError as ApiTypeError
from surogate_hub_sdk.exceptions import ApiValueError as ApiValueError
from surogate_hub_sdk.exceptions import ApiKeyError as ApiKeyError
from surogate_hub_sdk.exceptions import ApiAttributeError as ApiAttributeError
from surogate_hub_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from surogate_hub_sdk.models.acl import ACL as ACL
from surogate_hub_sdk.models.abort_presign_multipart_upload import AbortPresignMultipartUpload as AbortPresignMultipartUpload
from surogate_hub_sdk.models.access_key_credentials import AccessKeyCredentials as AccessKeyCredentials
from surogate_hub_sdk.models.action_run import ActionRun as ActionRun
from surogate_hub_sdk.models.action_run_list import ActionRunList as ActionRunList
from surogate_hub_sdk.models.auth_capabilities import AuthCapabilities as AuthCapabilities
from surogate_hub_sdk.models.authentication_token import AuthenticationToken as AuthenticationToken
from surogate_hub_sdk.models.branch_creation import BranchCreation as BranchCreation
from surogate_hub_sdk.models.branch_protection_rule import BranchProtectionRule as BranchProtectionRule
from surogate_hub_sdk.models.cherry_pick_creation import CherryPickCreation as CherryPickCreation
from surogate_hub_sdk.models.comm_prefs_input import CommPrefsInput as CommPrefsInput
from surogate_hub_sdk.models.commit import Commit as Commit
from surogate_hub_sdk.models.commit_creation import CommitCreation as CommitCreation
from surogate_hub_sdk.models.commit_list import CommitList as CommitList
from surogate_hub_sdk.models.commit_overrides import CommitOverrides as CommitOverrides
from surogate_hub_sdk.models.commit_record_creation import CommitRecordCreation as CommitRecordCreation
from surogate_hub_sdk.models.complete_presign_multipart_upload import CompletePresignMultipartUpload as CompletePresignMultipartUpload
from surogate_hub_sdk.models.config import Config as Config
from surogate_hub_sdk.models.credentials import Credentials as Credentials
from surogate_hub_sdk.models.credentials_list import CredentialsList as CredentialsList
from surogate_hub_sdk.models.credentials_with_secret import CredentialsWithSecret as CredentialsWithSecret
from surogate_hub_sdk.models.current_user import CurrentUser as CurrentUser
from surogate_hub_sdk.models.diff import Diff as Diff
from surogate_hub_sdk.models.diff_list import DiffList as DiffList
from surogate_hub_sdk.models.error import Error as Error
from surogate_hub_sdk.models.error_no_acl import ErrorNoACL as ErrorNoACL
from surogate_hub_sdk.models.external_login_information import ExternalLoginInformation as ExternalLoginInformation
from surogate_hub_sdk.models.external_principal import ExternalPrincipal as ExternalPrincipal
from surogate_hub_sdk.models.external_principal_creation import ExternalPrincipalCreation as ExternalPrincipalCreation
from surogate_hub_sdk.models.external_principal_list import ExternalPrincipalList as ExternalPrincipalList
from surogate_hub_sdk.models.find_merge_base_result import FindMergeBaseResult as FindMergeBaseResult
from surogate_hub_sdk.models.garbage_collection_config import GarbageCollectionConfig as GarbageCollectionConfig
from surogate_hub_sdk.models.garbage_collection_prepare_response import GarbageCollectionPrepareResponse as GarbageCollectionPrepareResponse
from surogate_hub_sdk.models.garbage_collection_rule import GarbageCollectionRule as GarbageCollectionRule
from surogate_hub_sdk.models.garbage_collection_rules import GarbageCollectionRules as GarbageCollectionRules
from surogate_hub_sdk.models.group import Group as Group
from surogate_hub_sdk.models.group_creation import GroupCreation as GroupCreation
from surogate_hub_sdk.models.group_list import GroupList as GroupList
from surogate_hub_sdk.models.hook_run import HookRun as HookRun
from surogate_hub_sdk.models.hook_run_list import HookRunList as HookRunList
from surogate_hub_sdk.models.import_creation import ImportCreation as ImportCreation
from surogate_hub_sdk.models.import_creation_response import ImportCreationResponse as ImportCreationResponse
from surogate_hub_sdk.models.import_location import ImportLocation as ImportLocation
from surogate_hub_sdk.models.import_status import ImportStatus as ImportStatus
from surogate_hub_sdk.models.installation_usage_report import InstallationUsageReport as InstallationUsageReport
from surogate_hub_sdk.models.internal_delete_branch_protection_rule_request import InternalDeleteBranchProtectionRuleRequest as InternalDeleteBranchProtectionRuleRequest
from surogate_hub_sdk.models.login_config import LoginConfig as LoginConfig
from surogate_hub_sdk.models.login_information import LoginInformation as LoginInformation
from surogate_hub_sdk.models.merge import Merge as Merge
from surogate_hub_sdk.models.merge_result import MergeResult as MergeResult
from surogate_hub_sdk.models.meta_range_creation import MetaRangeCreation as MetaRangeCreation
from surogate_hub_sdk.models.meta_range_creation_response import MetaRangeCreationResponse as MetaRangeCreationResponse
from surogate_hub_sdk.models.object_copy_creation import ObjectCopyCreation as ObjectCopyCreation
from surogate_hub_sdk.models.object_error import ObjectError as ObjectError
from surogate_hub_sdk.models.object_error_list import ObjectErrorList as ObjectErrorList
from surogate_hub_sdk.models.object_stage_creation import ObjectStageCreation as ObjectStageCreation
from surogate_hub_sdk.models.object_stats import ObjectStats as ObjectStats
from surogate_hub_sdk.models.object_stats_list import ObjectStatsList as ObjectStatsList
from surogate_hub_sdk.models.object_upload_mode import ObjectUploadMode as ObjectUploadMode
from surogate_hub_sdk.models.pagination import Pagination as Pagination
from surogate_hub_sdk.models.path_list import PathList as PathList
from surogate_hub_sdk.models.policy import Policy as Policy
from surogate_hub_sdk.models.policy_list import PolicyList as PolicyList
from surogate_hub_sdk.models.prepare_gc_uncommitted_request import PrepareGCUncommittedRequest as PrepareGCUncommittedRequest
from surogate_hub_sdk.models.prepare_gc_uncommitted_response import PrepareGCUncommittedResponse as PrepareGCUncommittedResponse
from surogate_hub_sdk.models.presign_multipart_upload import PresignMultipartUpload as PresignMultipartUpload
from surogate_hub_sdk.models.pull_request import PullRequest as PullRequest
from surogate_hub_sdk.models.pull_request_basic import PullRequestBasic as PullRequestBasic
from surogate_hub_sdk.models.pull_request_creation import PullRequestCreation as PullRequestCreation
from surogate_hub_sdk.models.pull_request_creation_response import PullRequestCreationResponse as PullRequestCreationResponse
from surogate_hub_sdk.models.pull_requests_list import PullRequestsList as PullRequestsList
from surogate_hub_sdk.models.range_metadata import RangeMetadata as RangeMetadata
from surogate_hub_sdk.models.ref import Ref as Ref
from surogate_hub_sdk.models.ref_list import RefList as RefList
from surogate_hub_sdk.models.refs_dump import RefsDump as RefsDump
from surogate_hub_sdk.models.refs_restore import RefsRestore as RefsRestore
from surogate_hub_sdk.models.repository import Repository as Repository
from surogate_hub_sdk.models.repository_creation import RepositoryCreation as RepositoryCreation
from surogate_hub_sdk.models.repository_dump_status import RepositoryDumpStatus as RepositoryDumpStatus
from surogate_hub_sdk.models.repository_list import RepositoryList as RepositoryList
from surogate_hub_sdk.models.repository_metadata_keys import RepositoryMetadataKeys as RepositoryMetadataKeys
from surogate_hub_sdk.models.repository_metadata_set import RepositoryMetadataSet as RepositoryMetadataSet
from surogate_hub_sdk.models.repository_restore_status import RepositoryRestoreStatus as RepositoryRestoreStatus
from surogate_hub_sdk.models.reset_creation import ResetCreation as ResetCreation
from surogate_hub_sdk.models.revert_creation import RevertCreation as RevertCreation
from surogate_hub_sdk.models.setup import Setup as Setup
from surogate_hub_sdk.models.setup_state import SetupState as SetupState
from surogate_hub_sdk.models.staging_location import StagingLocation as StagingLocation
from surogate_hub_sdk.models.staging_metadata import StagingMetadata as StagingMetadata
from surogate_hub_sdk.models.statement import Statement as Statement
from surogate_hub_sdk.models.stats_event import StatsEvent as StatsEvent
from surogate_hub_sdk.models.stats_events_list import StatsEventsList as StatsEventsList
from surogate_hub_sdk.models.storage_config import StorageConfig as StorageConfig
from surogate_hub_sdk.models.storage_uri import StorageURI as StorageURI
from surogate_hub_sdk.models.sts_auth_request import StsAuthRequest as StsAuthRequest
from surogate_hub_sdk.models.tag_creation import TagCreation as TagCreation
from surogate_hub_sdk.models.task_info import TaskInfo as TaskInfo
from surogate_hub_sdk.models.underlying_object_properties import UnderlyingObjectProperties as UnderlyingObjectProperties
from surogate_hub_sdk.models.update_object_user_metadata import UpdateObjectUserMetadata as UpdateObjectUserMetadata
from surogate_hub_sdk.models.update_token import UpdateToken as UpdateToken
from surogate_hub_sdk.models.upload_part import UploadPart as UploadPart
from surogate_hub_sdk.models.usage_report import UsageReport as UsageReport
from surogate_hub_sdk.models.user import User as User
from surogate_hub_sdk.models.user_creation import UserCreation as UserCreation
from surogate_hub_sdk.models.user_list import UserList as UserList
from surogate_hub_sdk.models.version_config import VersionConfig as VersionConfig

