apiVersion: v2
name: surogate-hub
description: A Helm chart for running Surogate Hub on Kubernetes
type: application
version: 1.0.0
appVersion: 2.0.0

home: https://surogate.ai
sources:
  - https://github.com/invergent-ai/surogate-hub
maintainers:
  - name: invergent
    email: maintainers@invergent.ai

annotations:
  artifacthub.io/category: storage
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: source
      url: https://github.com/invergent-ai/surogate-hub
    - name: support
      url: https://github.com/invergent-ai/surogate-hub/issues
  artifacthub.io/images: |
    - name: surogate-hub
      image: ghcr.io/invergent-ai/surogate-hub:latest
