/*
 * Surogate Hub API
 * Surogate Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.surogate.hub.clients.sdk;

import org.surogate.hub.clients.sdk.ApiException;
import org.surogate.hub.clients.sdk.model.BranchCreation;
import org.surogate.hub.clients.sdk.model.CherryPickCreation;
import org.surogate.hub.clients.sdk.model.Commit;
import org.surogate.hub.clients.sdk.model.DiffList;
import org.surogate.hub.clients.sdk.model.Error;
import org.surogate.hub.clients.sdk.model.Ref;
import org.surogate.hub.clients.sdk.model.RefList;
import org.surogate.hub.clients.sdk.model.ResetCreation;
import org.surogate.hub.clients.sdk.model.RevertCreation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BranchesApi
 */
@Disabled
public class BranchesApiTest {

    private final BranchesApi api = new BranchesApi();

    /**
     * Replay the changes from the given commit on the branch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cherryPickTest() throws ApiException {
        String repository = null;
        String branch = null;
        CherryPickCreation cherryPickCreation = null;
        Commit response = api.cherryPick(repository, branch, cherryPickCreation)
                .execute();
        // TODO: test validations
    }

    /**
     * create branch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBranchTest() throws ApiException {
        String repository = null;
        BranchCreation branchCreation = null;
        String response = api.createBranch(repository, branchCreation)
                .execute();
        // TODO: test validations
    }

    /**
     * delete branch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteBranchTest() throws ApiException {
        String repository = null;
        String branch = null;
        Boolean force = null;
        api.deleteBranch(repository, branch)
                .force(force)
                .execute();
        // TODO: test validations
    }

    /**
     * diff branch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void diffBranchTest() throws ApiException {
        String repository = null;
        String branch = null;
        String after = null;
        Integer amount = null;
        String prefix = null;
        String delimiter = null;
        DiffList response = api.diffBranch(repository, branch)
                .after(after)
                .amount(amount)
                .prefix(prefix)
                .delimiter(delimiter)
                .execute();
        // TODO: test validations
    }

    /**
     * get branch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBranchTest() throws ApiException {
        String repository = null;
        String branch = null;
        Ref response = api.getBranch(repository, branch)
                .execute();
        // TODO: test validations
    }

    /**
     * list branches
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listBranchesTest() throws ApiException {
        String repository = null;
        String prefix = null;
        String after = null;
        Integer amount = null;
        Boolean showHidden = null;
        RefList response = api.listBranches(repository)
                .prefix(prefix)
                .after(after)
                .amount(amount)
                .showHidden(showHidden)
                .execute();
        // TODO: test validations
    }

    /**
     * reset branch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resetBranchTest() throws ApiException {
        String repository = null;
        String branch = null;
        ResetCreation resetCreation = null;
        api.resetBranch(repository, branch, resetCreation)
                .execute();
        // TODO: test validations
    }

    /**
     * revert
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void revertBranchTest() throws ApiException {
        String repository = null;
        String branch = null;
        RevertCreation revertCreation = null;
        api.revertBranch(repository, branch, revertCreation)
                .execute();
        // TODO: test validations
    }

}
