/*
 * Surogate Hub API
 * Surogate Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.surogate.hub.clients.sdk;

import org.surogate.hub.clients.sdk.ApiException;
import org.surogate.hub.clients.sdk.model.Config;
import org.surogate.hub.clients.sdk.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigApi
 */
@Disabled
public class ConfigApiTest {

    private final ConfigApi api = new ConfigApi();

    /**
     * retrieve Surogate Hub configuration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConfigTest() throws ApiException {
        Config response = api.getConfig()
                .execute();
        // TODO: test validations
    }

}
