/*
 * Surogate Hub API
 * Surogate Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.surogate.hub.clients.sdk;

import org.surogate.hub.clients.sdk.ApiException;
import org.surogate.hub.clients.sdk.model.AuthenticationToken;
import org.surogate.hub.clients.sdk.model.Error;
import org.surogate.hub.clients.sdk.model.ExternalLoginInformation;
import org.surogate.hub.clients.sdk.model.ExternalPrincipal;
import org.surogate.hub.clients.sdk.model.ExternalPrincipalCreation;
import org.surogate.hub.clients.sdk.model.ExternalPrincipalList;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExternalApi
 */
@Disabled
public class ExternalApiTest {

    private final ExternalApi api = new ExternalApi();

    /**
     * attach external principal to user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserExternalPrincipalTest() throws ApiException {
        String userId = null;
        String principalId = null;
        ExternalPrincipalCreation externalPrincipalCreation = null;
        api.createUserExternalPrincipal(userId, principalId)
                .externalPrincipalCreation(externalPrincipalCreation)
                .execute();
        // TODO: test validations
    }

    /**
     * delete external principal from user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserExternalPrincipalTest() throws ApiException {
        String userId = null;
        String principalId = null;
        api.deleteUserExternalPrincipal(userId, principalId)
                .execute();
        // TODO: test validations
    }

    /**
     * perform a login using an external authenticator
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void externalPrincipalLoginTest() throws ApiException {
        ExternalLoginInformation externalLoginInformation = null;
        AuthenticationToken response = api.externalPrincipalLogin()
                .externalLoginInformation(externalLoginInformation)
                .execute();
        // TODO: test validations
    }

    /**
     * describe external principal by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getExternalPrincipalTest() throws ApiException {
        String principalId = null;
        ExternalPrincipal response = api.getExternalPrincipal(principalId)
                .execute();
        // TODO: test validations
    }

    /**
     * list user external policies attached to a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listUserExternalPrincipalsTest() throws ApiException {
        String userId = null;
        String prefix = null;
        String after = null;
        Integer amount = null;
        ExternalPrincipalList response = api.listUserExternalPrincipals(userId)
                .prefix(prefix)
                .after(after)
                .amount(amount)
                .execute();
        // TODO: test validations
    }

}
