/*
 * Surogate Hub API
 * Surogate Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.surogate.hub.clients.sdk;

import org.surogate.hub.clients.sdk.ApiException;
import org.surogate.hub.clients.sdk.model.Error;
import org.surogate.hub.clients.sdk.model.ImportCreation;
import org.surogate.hub.clients.sdk.model.ImportCreationResponse;
import org.surogate.hub.clients.sdk.model.ImportStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImportApi
 */
@Disabled
public class ImportApiTest {

    private final ImportApi api = new ImportApi();

    /**
     * cancel ongoing import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importCancelTest() throws ApiException {
        String repository = null;
        String branch = null;
        String id = null;
        api.importCancel(repository, branch, id)
                .execute();
        // TODO: test validations
    }

    /**
     * import data from object store
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importStartTest() throws ApiException {
        String repository = null;
        String branch = null;
        ImportCreation importCreation = null;
        ImportCreationResponse response = api.importStart(repository, branch, importCreation)
                .execute();
        // TODO: test validations
    }

    /**
     * get import status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importStatusTest() throws ApiException {
        String repository = null;
        String branch = null;
        String id = null;
        ImportStatus response = api.importStatus(repository, branch, id)
                .execute();
        // TODO: test validations
    }

}
