/*
 * Surogate Hub API
 * Surogate Hub API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.surogate.hub.clients.sdk;

import org.surogate.hub.clients.sdk.ApiException;
import org.surogate.hub.clients.sdk.model.AuthCapabilities;
import org.surogate.hub.clients.sdk.model.BranchProtectionRule;
import org.surogate.hub.clients.sdk.model.CommPrefsInput;
import org.surogate.hub.clients.sdk.model.CommitRecordCreation;
import org.surogate.hub.clients.sdk.model.CredentialsWithSecret;
import org.surogate.hub.clients.sdk.model.Error;
import java.io.File;
import org.surogate.hub.clients.sdk.model.GarbageCollectionConfig;
import org.surogate.hub.clients.sdk.model.GarbageCollectionPrepareResponse;
import org.surogate.hub.clients.sdk.model.GarbageCollectionRules;
import org.surogate.hub.clients.sdk.model.InstallationUsageReport;
import org.surogate.hub.clients.sdk.model.InternalDeleteBranchProtectionRuleRequest;
import org.surogate.hub.clients.sdk.model.ObjectStageCreation;
import org.surogate.hub.clients.sdk.model.ObjectStats;
import org.surogate.hub.clients.sdk.model.PrepareGCUncommittedRequest;
import org.surogate.hub.clients.sdk.model.PrepareGCUncommittedResponse;
import org.surogate.hub.clients.sdk.model.RefsDump;
import org.surogate.hub.clients.sdk.model.RefsRestore;
import org.surogate.hub.clients.sdk.model.RepositoryMetadataKeys;
import org.surogate.hub.clients.sdk.model.RepositoryMetadataSet;
import org.surogate.hub.clients.sdk.model.Setup;
import org.surogate.hub.clients.sdk.model.SetupState;
import org.surogate.hub.clients.sdk.model.StatsEventsList;
import org.surogate.hub.clients.sdk.model.StorageConfig;
import org.surogate.hub.clients.sdk.model.StorageURI;
import org.surogate.hub.clients.sdk.model.VersionConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InternalApi
 */
@Disabled
public class InternalApiTest {

    private final InternalApi api = new InternalApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBranchProtectionRulePreflightTest() throws ApiException {
        String repository = null;
        api.createBranchProtectionRulePreflight(repository)
                .execute();
        // TODO: test validations
    }

    /**
     * create commit record
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCommitRecordTest() throws ApiException {
        String repository = null;
        CommitRecordCreation commitRecordCreation = null;
        api.createCommitRecord(repository, commitRecordCreation)
                .execute();
        // TODO: test validations
    }

    /**
     * creates symlink files corresponding to the given directory
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSymlinkFileTest() throws ApiException {
        String repository = null;
        String branch = null;
        String location = null;
        StorageURI response = api.createSymlinkFile(repository, branch)
                .location(location)
                .execute();
        // TODO: test validations
    }

    /**
     * delete repository metadata
     *
     * Delete specified keys from the repository&#39;s metadata. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteRepositoryMetadataTest() throws ApiException {
        String repository = null;
        RepositoryMetadataKeys repositoryMetadataKeys = null;
        api.deleteRepositoryMetadata(repository, repositoryMetadataKeys)
                .execute();
        // TODO: test validations
    }

    /**
     * Dump repository refs (tags, commits, branches) to object store Deprecated: a new API will introduce long running operations 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void dumpRefsTest() throws ApiException {
        String repository = null;
        RefsDump response = api.dumpRefs(repository)
                .execute();
        // TODO: test validations
    }

    /**
     * list authentication capabilities supported
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAuthCapabilitiesTest() throws ApiException {
        AuthCapabilities response = api.getAuthCapabilities()
                .execute();
        // TODO: test validations
    }

    /**
     * get information of gc settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGarbageCollectionConfigTest() throws ApiException {
        GarbageCollectionConfig response = api.getGarbageCollectionConfig()
                .execute();
        // TODO: test validations
    }

    /**
     * get version of Surogate Hub server
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLakeFSVersionTest() throws ApiException {
        VersionConfig response = api.getLakeFSVersion()
                .execute();
        // TODO: test validations
    }

    /**
     * return a Surogate Hub metadata object by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMetadataObjectTest() throws ApiException {
        String repository = null;
        String objectId = null;
        String type = null;
        Boolean presign = null;
        File response = api.getMetadataObject(repository, objectId, type)
                .presign(presign)
                .execute();
        // TODO: test validations
    }

    /**
     * check if the Surogate Hub installation is already set up
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSetupStateTest() throws ApiException {
        SetupState response = api.getSetupState()
                .execute();
        // TODO: test validations
    }

    /**
     * retrieve Surogate Hub storage configuration
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getStorageConfigTest() throws ApiException {
        StorageConfig response = api.getStorageConfig()
                .execute();
        // TODO: test validations
    }

    /**
     * get usage report summary
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUsageReportSummaryTest() throws ApiException {
        InstallationUsageReport response = api.getUsageReportSummary()
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void internalCreateBranchProtectionRuleTest() throws ApiException {
        String repository = null;
        BranchProtectionRule branchProtectionRule = null;
        api.internalCreateBranchProtectionRule(repository, branchProtectionRule)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void internalDeleteBranchProtectionRuleTest() throws ApiException {
        String repository = null;
        InternalDeleteBranchProtectionRuleRequest internalDeleteBranchProtectionRuleRequest = null;
        api.internalDeleteBranchProtectionRule(repository, internalDeleteBranchProtectionRuleRequest)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void internalDeleteGarbageCollectionRulesTest() throws ApiException {
        String repository = null;
        api.internalDeleteGarbageCollectionRules(repository)
                .execute();
        // TODO: test validations
    }

    /**
     * get branch protection rules
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void internalGetBranchProtectionRulesTest() throws ApiException {
        String repository = null;
        List<BranchProtectionRule> response = api.internalGetBranchProtectionRules(repository)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void internalGetGarbageCollectionRulesTest() throws ApiException {
        String repository = null;
        GarbageCollectionRules response = api.internalGetGarbageCollectionRules(repository)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void internalSetGarbageCollectionRulesTest() throws ApiException {
        String repository = null;
        GarbageCollectionRules garbageCollectionRules = null;
        api.internalSetGarbageCollectionRules(repository, garbageCollectionRules)
                .execute();
        // TODO: test validations
    }

    /**
     * post stats events, this endpoint is meant for internal use only
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postStatsEventsTest() throws ApiException {
        StatsEventsList statsEventsList = null;
        api.postStatsEvents(statsEventsList)
                .execute();
        // TODO: test validations
    }

    /**
     * save lists of active commits for garbage collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void prepareGarbageCollectionCommitsTest() throws ApiException {
        String repository = null;
        GarbageCollectionPrepareResponse response = api.prepareGarbageCollectionCommits(repository)
                .execute();
        // TODO: test validations
    }

    /**
     * save repository uncommitted metadata for garbage collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void prepareGarbageCollectionUncommittedTest() throws ApiException {
        String repository = null;
        PrepareGCUncommittedRequest prepareGCUncommittedRequest = null;
        PrepareGCUncommittedResponse response = api.prepareGarbageCollectionUncommitted(repository)
                .prepareGCUncommittedRequest(prepareGCUncommittedRequest)
                .execute();
        // TODO: test validations
    }

    /**
     * Restore repository refs (tags, commits, branches) from object store. Deprecated: a new API will introduce long running operations 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void restoreRefsTest() throws ApiException {
        String repository = null;
        RefsRestore refsRestore = null;
        api.restoreRefs(repository, refsRestore)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setGarbageCollectionRulesPreflightTest() throws ApiException {
        String repository = null;
        api.setGarbageCollectionRulesPreflight(repository)
                .execute();
        // TODO: test validations
    }

    /**
     * set repository metadata
     *
     * Set repository metadata. This will only add or update the provided keys, and will not remove any existing keys. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setRepositoryMetadataTest() throws ApiException {
        String repository = null;
        RepositoryMetadataSet repositoryMetadataSet = null;
        api.setRepositoryMetadata(repository, repositoryMetadataSet)
                .execute();
        // TODO: test validations
    }

    /**
     * setup Surogate Hub and create a first user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setupTest() throws ApiException {
        Setup setup = null;
        CredentialsWithSecret response = api.setup(setup)
                .execute();
        // TODO: test validations
    }

    /**
     * setup communications preferences
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setupCommPrefsTest() throws ApiException {
        CommPrefsInput commPrefsInput = null;
        api.setupCommPrefs(commPrefsInput)
                .execute();
        // TODO: test validations
    }

    /**
     * stage an object&#39;s metadata for the given branch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void stageObjectTest() throws ApiException {
        String repository = null;
        String branch = null;
        String path = null;
        ObjectStageCreation objectStageCreation = null;
        ObjectStats response = api.stageObject(repository, branch, path, objectStageCreation)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadObjectPreflightTest() throws ApiException {
        String repository = null;
        String branch = null;
        String path = null;
        api.uploadObjectPreflight(repository, branch, path)
                .execute();
        // TODO: test validations
    }

}
